---
  - name: KnockD | Install package
    apt: pkg="knockd"
    become: yes
    tags:
      - knockd

  - name: KnockD | Template /etc/knockd.conf
    template: src="{{role_dir}}/templates/knockd.conf.{{knock_firewall_type}}.j2" dest="/etc/knockd.conf"
    become: yes
    tags:
      - knockd

  - name: KnockD | Patch /etc/default/knockd
    lineinfile: dest=/etc/default/knockd  regexp="{{item.regexp}}" line="{{item.line}}" insertafter="{{item.insertafter | default('EOF')}}"
    with_items: "{{knock_default_props | default([])}}"
    become: yes
    tags:
      - knockd

  - name: KnockD | Restart service
    service: name="knockd" state="restarted" enabled="yes"
    become: yes
    when: docker_test is not defined
    tags:
      - knockd

  - block:

    - name: KnockD | Delete hardened ports from the world
      shell: ufw delete allow {{item.port}}/tcp
      with_items: "{{knock_ports | default([])}}"
      when: option_close_hardened_ports
      tags:
        - knockd

    when: knock_firewall_type == "ufw" and docker_test is not defined

  - block:

    - name: KnockD | Delete hardened ports from the world
      shell: /sbin/iptables -D INPUT -s %IP% -p tcp --dport {{item.port}} -j ACCEPT
      with_items: "{{knock_ports | default([])}}"
      when: option_close_hardened_ports
      tags:
        - knockd

    when: knock_firewall_type == "iptables" and docker_test is not defined
